/*
CSS POSTPROCESSOR
Copyright 2015 Alex Bobrov
Version 1.0

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

(function(){function q(a,c,e,d){b[a][c]=[];b[a][c][0]=d+'("&a","&b")';b[a][c][1]=[];b[a][c][3]=[];b[a][c][4]=[];b[a][c][5]=e;b[a][c][7]=[];g.update({n:a,v:c})}function t(a){var c;(window.addEventListener||window.attachEvent)(a,function(){clearTimeout(c);c=setTimeout(function(){p()},g.defaults.resizing)},!1)}function p(){if(g.reset.length)for(var a=0;a<g.reset.length;a++)"alignment"==g.reset[a].v||"selfwidth"==g.reset[a].v||"selfheight"==g.reset[a].v?function(a){setTimeout(function(){g.set(g.reset[a].n,
g.reset[a].v)},100)}(a):g.set(g.reset[a].n,g.reset[a].v)}function u(a,c){var e=g.convert_to_raw_css(a,c);try{document.getElementById(c).innerHTML=e}catch(d){document.getElementById(c).styleSheet.cssText=e}"loading"!=document.readyState?v(c):document.addEventListener("DOMContentLoaded",function(a){v(c)});w()}function w(){"complete"==document.readyState?p():setTimeout(function(){w()},20)}function v(a){p();document.getElementsByTagName("html")[0].style.visibility="visible";try{var c=document.createEvent("HTMLEvents");
c.initEvent("css_ready",!0,!0);c.id=a;document.dispatchEvent(c)}catch(e){try{c=document.createEventObject(),c.id=a,document.fireEvent("css_ready",c)}catch(d){}}}function n(a){try{return eval(a)}catch(c){return a}}function x(a,c){var e="";c&&(c=c.split(","));for(var d in a){for(var b=d.split(","),f="",h=0;h<b.length;h++)if(c)for(var k=0;k<c.length;k++)f+=c[k]+" "+b[h]+",";else f+=b[h]+",";a[d].ele&&(e+=x(a[d].ele,f.slice(0,-1)));a[d].val&&(e+=f.slice(0,-1)+"{"+a[d].val+"}\n")}return e}function y(a,
c,e){var d=a[c].match(/^([^{]*){([^{]*){([^}]*)/);e[d[1]]||(e[d[1]]={});e[d[1]].ele={};var b=d[1].match(/(.*):*/)[1];/&(:.*)/.test(d[2])&&(b+=d[2].match(/&(:.*)/)[1]);e[b]||(e[b]={});e[b].ele={};/&/.test(d[2])?d[3].length&&(e[b].val=e[b].val?e[b].val+(";"+d[3]):d[3]):e[b].ele[d[2]]={val:d[3]};for(c+=1;c<a.length;c++)if(/{.*{/.test(a[c])&&!/@/.test(a[c])){var f=y(a,c,e[d[1]].ele);c=f.index;e[b].ele=f.nest}else if(/{.*}/.test(a[c]))f=a[c].match(/^([^{]*){([^}]*)/),/&/.test(f[1])?e[b]&&e[b].val?e[b].val+=
";"+f[2]:e[b]={val:f[2]}:e[b].ele[f[1]]?e[b].ele[f[1]].val+=";"+f[2]:e[b].ele[f[1]]={val:f[2]};else break;return{index:c,nest:e}}function z(a,c,e,d,b){for(var f=[],h=0;h<document.styleSheets.length;h++){var k=document.styleSheets[h];if(k.ownerNode.id==a){var l=0;do{var g=k.cssRules?k.cssRules[l]:k.rules[l];g&&g.selectorText==c&&f.push(g);l++}while(g)}}f.length&&A(f[f.length-1],e,d,b)}function A(a,c,e,d){c=c.toString().split(";");for(var b=0;b<c.length;b++){e&&(c[b]=e+c[b]+d);var f=c[b].split(":"),
h=f[0];f[0].match(/-/)&&(f[0]=f[0].replace(/-(.)/,function(a){return a.toUpperCase()}).replace(/-/,""));var k;k=/ !important/.test(f[1])?f[1].slice(0,-11):f[1];k!=f[1]?a.style.setProperty(h,k,"important"):a.style[f[0]]=f[1]}}function B(){var a;if(window.XMLHttpRequest)a=new XMLHttpRequest,a.overrideMimeType&&a.overrideMimeType("text/html");else if(window.ActiveXObject){try{a=new ActiveXObject("Msxml2.XMLHTTP")}catch(c){try{a=new ActiveXObject("Microsoft.XMLHTTP")}catch(b){}}a.setRequestHeader("X-Requested-With",
"XMLHttpRequest")}return a}var b=b||{},g=window.css||{defaults:{resizing:50,debug:1},reset:[],vars:{w:function(a,c){if(arguments.length){c||(c=0);var b=a.match(/.*('.*').*/);b&&(a=b[1]);var d=document.body?document.body.querySelectorAll(n(a)):[];return d.length?(d=d[c].clientWidth,b&&(d=b[0].replace(new RegExp(a,"g"),d)),n(d)):0}return document.documentElement.clientWidth||document.body.clientWidth},h:function(a,c){if(arguments.length){c||(c=0);var b=a.match(/.*('.*').*/);b&&(a=b[1]);var d=document.body?
document.body.querySelectorAll(n(a)):[];return d.length?(d=d[c].clientHeight,b&&(d=b[0].replace(new RegExp(a,"g"),d)),n(d)):0}return window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight},o:function(){return window.orientation||0},a:function(a,c){var b=document.body?document.body.querySelectorAll(n(a)):[];if(b.length)for(var d=0;d<b.length;d++)if("table-cell"!=window.getComputedStyle(b[d]).getPropertyValue("display"))for(var g=b[d].clientHeight,f=0;f<b[d].children.length;f++){var h=
b[d].children[f].getBoundingClientRect().height;"fixed"!=b[d].children[f].style.position&&"absolute"!=b[d].children[f].style.position&&(b[d].children[f].style.position="relative");b[d].children[f].style.top="middle"==c?(g-h)/2+"px":g-h+"px"}return c}},open:function(a,b){document.getElementsByTagName("html")[0].style.visibility="hidden";this.init||(g.init=1,t("orientationchange"),t("resize"));if("#"==a.substring(0,1))u(document.getElementById(a.substring(1)).innerHTML,a.substring(1));else{b=b?"?R="+
+new Date:"";var e=document.createElement("style");e.id=/\/(\w+)\.\w+$/.exec(a)[1];var d=B();d.onreadystatechange=function(){4==d.readyState&&u(d.responseText,e.id)};d.open("GET",a+b,!0);d.send("");document.getElementsByTagName("head")[0].appendChild(e)}},compute:function(a,c,e,d,r,f){var h=c.match(/\$\[{0,1}\w+[^;^}]*/g);if(h)for(f=0;f<h.length;f++){r=/ !important\]/.test(h[f]);h[f]=h[f].replace(/\$\[*(\w*(\(.*\))*)( !important)*\]*.*/g,"$1");d=h[f];var k=void 0,l=d.indexOf("(");0<l&&(k=d.substring(l).slice(0,
-1).slice(1),d=d.substring(0,l));d=[d,k];g.defaults.debug&&(b[a][d[0]]||console.log("Variable "+d[0]+" is not defined"));e&&b[a][d[0]][1].push(e);if(d[1]||b[a][d[0]][5])if(d[1]&&d[1]!=b[a][d[0]][5]||!b[a][d[0]][6]){b[a][d[0]][2]=b[a][d[0]][0];k=(d[1]||b[a][d[0]][5]).split(",");for(l=0;l<k.length;l++){/&self/.test(k[l])&&(k[l]=k[l].replace(/&self/g,"'"+c.match(/^[^{]*/)+"'"));var m=new RegExp("&"+String.fromCharCode(97+l),"g");b[a][d[0]][2]=b[a][d[0]][2].replace(m,k[l])}b[a][d[0]][2]=n(b[a][d[0]][2]);
d[1]&&d[1]!=b[a][d[0]][5]||(b[a][d[0]][6]=b[a][d[0]][2]);b[a][d[0]][7].push(d[1])}else b[a][d[0]][2]=b[a][d[0]][6],b[a][d[0]][7].push(b[a][d[0]][5]);else b[a][d[0]][2]||(b[a][d[0]][2]=b[a][d[0]][0],b[a][d[0]][2]=this.compute(a,b[a][d[0]][2],"$"+d[0]));d[1]=d[1]?"\\("+d[1].replace(/(\+|\*|\(|\))/g,"\\$1")+"\\)":"";m=new RegExp("([^;^{]+)\\$\\[*"+d[0]+d[1]+"\\]*([^}^;]*)");k=c.match(m);/\$/.test(b[a][d[0]][2]);k&&(b[a][d[0]][3].push(k[1]),b[a][d[0]][4].push(k[2]));r?(m=new RegExp("\\$\\[*"+d[0]+d[1]+
"[ !important\\]]*\\]*"),c=c.replace(m,b[a][d[0]][2].replace(/;/g," !important;")+" !important")):(m=new RegExp("\\$\\[*"+d[0]+d[1]+"\\]*"),c=c.replace(m,b[a][d[0]][2]))}else if(d)for(k=d.split(","),l=0;l<k.length;l++)/&self/.test(k[l])&&(k[l]=k[l].replace(/&self/g,"'"+r+"'")),m=new RegExp("&"+String.fromCharCode(97+l),"g"),c=c.replace(m,k[l]);return n(c)},get:function(a,c){return b[a][c][0]},get_computed:function(a,c){return b[a][c][2]},set:function(a,c,e){g.defaults.debug&&(c||console.log('"a" is not defined: '+
c),b[a][c]||console.log("Variable "+c+" is not defined"));e&&(b[a][c][0]=e);if(b[a][c][1].length)if(b[a][c][5])for(e=0;e<b[a][c][1].length;e++){var d=this.compute(a,b[a][c][0],0,b[a][c][7][e],b[a][c][1][e],c);b[a][c][2]=d;/\$[^=]/.test(b[a][c][1][e])?this.set(a,b[a][c][1][e].substring(1),b[a][b[a][c][1][e].substring(1)][0]):z(a,b[a][c][1][e],b[a][c][2],b[a][c][3][e],b[a][c][4][e])}else for(b[a][c][2]=this.compute(a,b[a][c][0]),e=0;e<b[a][c][1].length;e++)/\$[^=]/.test(b[a][c][1][e])?this.set(a,b[a][c][1][e].substring(1),
b[a][b[a][c][1][e].substring(1)][0]):z(a,b[a][c][1][e],b[a][c][2],b[a][c][3][e],b[a][c][4][e])},update:function(){for(var a=0;a<arguments.length;a++)g.reset.push(arguments[a])},convert_to_raw_css:function(a,c){b[c]||(b[c]={});a=a.replace(/(\/\*[\s\S]*?\*\/)/g,"").replace(/(\s+)?\/\/(.*)/g,"").replace(/\s\s*/g," ").replace(/\s*([{;,:])\s*/g,"$1").replace(/[\s;]*}\s*/g,"}\n").replace(/(\@[^{]*{)/g,"$1\n").replace(/^\s*/,"");do a=a.replace(/({)([^{^\n]*{[^{^\n]*{)/g,"$1&{}\n$2");while(a.match(/({)([^{^\n]*{[^{^\n]*{)/));
a=a.replace(/\n$/,"");a=a.replace(/\n\s/,"\n");a=a.replace(/vertical-align:(middle|bottom)/g,"vertical-align:$alignment(&self,$1)");a=a.replace(/:height\(([^;^}]*)\)/g,":$selfheight($1,0)");a=a.replace(/:width\(([^;^}]*)\)/g,":$selfwidth($1,0)");var e=a.split("\n"),d="";q(c,"selfwidth","&self,0","css.vars.w");q(c,"selfheight","&self,0","css.vars.h");q(c,"alignment","&self,bottom","css.vars.a");for(var g=0;g<e.length;g++){if(/^\$/.test(e[g])){var f=e[g].match(/^\$([^{^\(]*).*{(.*)}/);f[1]=f[1].split(",");
for(var h=0;h<f[1].length;h++)if(b[c][f[1][h]]=[],b[c][f[1][h]][0]=f[2],b[c][f[1][h]][1]=[],b[c][f[1][h]][3]=[],b[c][f[1][h]][4]=[],/\){/.test(f[0])){var k=f[0].match(/\(([^\)]*)\)/);b[c][f[1][h]][5]=k[1];b[c][f[1][h]][7]=[]}e.splice(g,1)}else if(/{.*[^$]+{/.test(e[g])&&!/@/.test(e[g]))f=y(e,g,{}),e.splice.apply(e,[g,f.index-g+1].concat(x(f.nest,"").replace(/\n$/,"").split("\n")));else{if(/\$[^=]/.test(e[g])){f=e[g].match(/([^{]*){/)[1].replace(/,\s*/,", ");h=this.compute(c,e[g],f);if(/selfwidth/.test(h)||
/selfheight/.test(h))h=this.compute(c,h,f);d+="\n"+h}else d+="\n"+e[g];e.splice(g,1)}g--}return d}};window.css=g;window.css_vars=b;g.update_vars=p})();